### ISSUE TITLE
[Troubleshooting] Weekly Assignments/Deep Dives not working

### ISSUE THREAD

**Issue by Toast2020** [0P3N50URC3-F0R3V3R/blackbeard#3]
Hi there, I just tried your program but can't get it to work. I'm wondering if I'm setting it up wrong or if it no longer works with the latest game version?

My blue rank is 20 and I have promoted my driller, but I can't get weekly assignments/deep dives to show up. Free beer works though, but not the other events.
![1](https://user-images.githubusercontent.com/101273819/157477238-16b97946-75fd-4f5c-a1d8-8b948155deb5.png)
![2](https://user-images.githubusercontent.com/101273819/157477245-7fe1e02b-f1d7-4370-8096-c44934f89f1c.png)

I've tried both 127.0.0.1 and my LAN IP in my hosts file and get the same result. With both XAMPP and Blackbeard running (as admin), if I open https://localhost/ in firefox I just see a web page with "ROCK AND STONES!" and nothing else.

Blackbeard seems to be writing to the htdocs files, so I'm not sure what's wrong. Here are my setups:

![3](https://user-images.githubusercontent.com/101273819/157478518-fb56845a-ab7e-43f7-ad7a-cac1ebbca6ab.png)
![4](https://user-images.githubusercontent.com/101273819/157478524-fc256ddf-1f5a-4c21-8a3b-84166c94f688.png)

Thanks in advance!

**Comment by 0P3N50URC3-F0R3V3R** [comment]
As you seen in the readme in github, currently only supported U35, the latest version is not working.

**Comment by Toast2020** [comment]
Thanks for the reply! I mistakenly thought that Blackbeard was required to play deep dives with Goldberg, but I have since found out about "disable_lan_only.txt" and now the official weeklies/deep dives work fine. So don't worry about it!
