### ISSUE TITLE
UI for easier use

### ISSUE THREAD

**Issue by Ravest95** [0P3N50URC3-F0R3V3R/blackbeard#5]
I don't expect any changes to current UI, just dumping some ideas on how it should look/function.

![Visuals](https://user-images.githubusercontent.com/105741067/226492754-eec73358-bd7d-4318-b8ba-c3f2db64d492.png)

Basic idea was to allow the replay of dd with 100% accuracy + events. (Mods allow to start dd, but it will be different). Usually events are the thing people try to replay to get event hats, I jammed dd for personal reasons.
1) The program should load info from a folder "DeepDives". That folder will contain separate file named "1" to "270". Each file will contain xml info on version, seed, region, etc. (In the event of dumping the project other people just need to add new files for the program to load, or for ability to make custom dd).
2) Segregate tabs "Version, Deep Dive, Event, Assignment, Settings, Help" for easier navigation.
"Version" - identifying required game version + manifest to download, maybe add link to launch the game from the program since you need to restart the game to apply the changes.
"Deep Dive" - you can see the picture. (maybe colour coded dd for updates)
"Event" - deep dive will suggest the event for dd, but will allow to use any. (Free beer is a separate thing not tied to events at all, but it should be used by the program as event to remove the overlapping signs above the bar)
"Assignment" - self-explanatory
"Settings" - settings for the program. (should be saved in text editable file (.ini, .cfg)) Window size, Window position, Hide pop Up messages. 
3) The only important thing I really want is not tying UI to pixels on 2560x1600 it looks bad.

**Comment by 0P3N50URC3-F0R3V3R** [comment]
Hellor here too :D It is not bad at all, IMHO :D I did already considered the UI, on separate tabs before, i might do it one day, the main screen gets a bit crowded... But when i did put them into separate tabs it was too little on that page so i did not bothered with it... but now it could be a good idea as the features are getting larger :D

Some invisions:
1. You wont need xml, there is INI files that i am using, currently the settings and other stuff are not soo much, even the deep dives... so momentalery will be hardcoded to your excel.

2. Tabs are generally good ideas, however: I dont have control over the seed numbers and map levelnames.(IDK what part of the seed does what, so i cannot list the map names) Also theese event names are officials mostly so they are hardcoded... So why i would need to breadcrumb the data to fields? :\  BUT! If you can write a generator that has controllable stats, (AKA you know what the seed does exactly) you might implement it into the program i am open for it, but i am programming only in lazarus nowadays(I know this is an old language, but mainly i can code this only XD)

3. I will create an ui to can be uniformly maximize minimize and reszie... i just sis not wanted to bother with it before XD  it can be done... 

Generally, the Level generator "editor" would be a nice one, but keep in mind that it would require different cliens different setting, that is a HELLUWA lot work, but i would like to see it in action :D :D

The next relase will use the same old overcrowded main screen a of now, but i will slowli implement some things from theese ideas :D i like them :D

**Comment by 0P3N50URC3-F0R3V3R** [comment]
Currently it is looks like this, (OFC it will change i just got to attend to this today so that is what i modified within yet, but it is a SUBJECT TO CHANGE)

![image](https://user-images.githubusercontent.com/94479523/226497547-e4c3f42a-f511-48cc-8a23-990bc176fd9d.png)

**Comment by 0P3N50URC3-F0R3V3R** [comment]
I am thinking of few tabs as of now...

Like Daemon-> DeepDives -> Assignments ->Events ->Notes -> Console 
(there is one now, but it is not used before :D i just wanted to implement at the end...)
Also there will be notification bubbles if i can solve it as i want it...

**Comment by Ravest95** [comment]
Also some things, idk if you know them now.

"Seed" and "SeedV2" are the same thing. It is not a deep dive and deep dive elite, old versions of the game used "Seed", but a bit later devs switched it to "SeedV2" keeping the "Seed" for some reason. There is no need to keep "Seed" at all, exept if you want to allow old versions to emulate the dives. Thats why I kept the command in full form -> {"Seed":3612673878,"SeedV2":3612673878,"ExpirationTime":"2100-01-01T00:00:00Z"} where "Seed" and "SeedV2" duplicated to allow functionality for old and new versions.

Deep Dive generation will be impossiable to figure out without looking into source. As my idea was to preserve old dives for replay (sort of justify the tool existence) I tried to figure out how to keep the dives identical to when I first played them. Deep Dive generation is tied to the game version. Every update can change its generation (usually adding new mineral, enemy, etc, not only cave rooms). All updates of a season (lets say "Update 34") will have the same dives. A small patch can change things a little, but it is usually 1-2 first dives (Deives 112 and 111 will use "1.35.63432.0", when 113 - "1.35.69455.0", because there was a change in the generation process), for a user that means downloading 2 different versions of the same update just to preserve the original dive for those 1-2 missions. For me it is fine, but I do understand it will not be for others (thats why I color coded the updates, different shades of color differnt version). To minimise the amount of versions I took the last one of the update (It has most fixes) and I tested every deep dive manually, comparing it to playthrough on original version. It takes a lot of time and I didnt finish everything (I kinda forget about checking things when I play for fun). My way is to keep the shape of every room, position of the minerals, some static enemies (BetC, Spitballer, Breeder) will be randomised no matter what. I still have no idea why they switch position/dissapear (might be tied to time).

Setting time for dd/assignment is neat but ordinary people will not get the seconds. Better way to use hours. Even then is it a good idea? I didnt test it maybe you know, when the time runs out game will not block the dd/assignment and will not load new one. Game needs restart to load changes, so that means timer is irrelevent, since all it does, that official time is over. For multiplayer only host needs xampp to create deep dives, those who will join will load info from him. That means they will never see the clock.

**Comment by 0P3N50URC3-F0R3V3R** [comment]
Okaaay :D so
- The point in this tool is that it should be compatible with older versions.(I might just broke the thing as of now but i will fix it to the other versions too i mean the webserver paths)
- I fixed the labels for the V2 seeds. :D So not "elite" anymore. Its just Seed v1 and Seedv2(in the ININ i will leave as it is, it is not visible basicly...)
- I did redesigned the interface to represent the interface with tabs :D it looks i guess better...
- I must point out that the tool will be provided as it is, the "lets download other parts" are will be not my concern XD
- About the hosts and clients relation in regarding the clock: If the other peoples(Clients) sets their HOSTS file to point to your server, they will see the normal DD times that you set with calendar. We are tested this :\ 

Also, if the assigmnens are expiring, blackberad will auto generate a new seed for the game.(it can be turned ott tho, but that is the reason for the whole countdown and resetting, and daemon why blackbeard can run in background.) So if they exit and reload the game there will be new deepdives... The seconds are mostly for the program, and it was more simpler to write it this way. But if every participant in their hosts file sets the DD blackbeard xampp ip server, you can host a DD emulated server that will auto generate new missions for all peoples who is using the same server IP (like on lan or VPN or radmin)...

**Comment by 0P3N50URC3-F0R3V3R** [comment]
I did pushed out a somewhat beta version, that is already useable. It is not the final version, but works with new and old versions - i  tested it. I will continue the work on it thru the next weeks. Until the next release, it can be used as-it-is

**Comment by Ravest95** [comment]
Do you mind some discord talk? "Ravest95#1795" It would be easier for me to explain some thing.

**Comment by 0P3N50URC3-F0R3V3R** [comment]
Erm. I rather not. Since i am not using DC.

**Comment by Ravest95** [comment]
ye Ive noticed the console poping up for a sec later.  You don't need to explain to me anything, or repeat that it is beta. Like I made something better and you need to protect your work. Just say no that is stupid or something. I do inderstand how some things work, but I am looking from a perspective of ordinary user and they are generaly stupid. I had so much shit for asking people to share drg save files to get dive seeds. 70% accused me of trying to hack them so ye. When someone will take your program they will be overwhelmed by a lot of words and buttons, requerments etc, I'm trying to give you some insite on that.

**Comment by 0P3N50URC3-F0R3V3R** [comment]
I would never say that...(i was never "monitor fight" with phrases like: "Do a better if you can" or such ) And besides, i've seen your video, you are recreated "my work" very well.... hell, you are even made a very good and small XAMMP...(I was not able to) 

:D if i would not like to see any insights i woul not reach out for you, easy... i just dont think that some ini or log file could cause any problem as leftovers, but i removed them and edited the thing. :D 

I did changed the RC1 release with ALMOST all that you are asked, the xampp_contol.ini was the same in your archive too... i mean i've not seen any difference but it is not causing any problems imho...

I will leave the CRT files in htdocs now. I would need to modify both Blackbeard and the Bat files so i wont bother with it as of now, i will remove them in the next release... i wont fix it today i am tired a bit i was doing this the whole day for now :D

I left in your Deepdive-Emulator\Deepdive-List.xlsx file, but i removed my modified ones.
So the archive is new. You can redownload.

**Comment by Ravest95** [comment]
It's my OCD man. I can't stand those logs, that are not made by my system or settings, that are not picked by me. Even if they do nothing. My personal brain damage.

Also did try to set up xampp on PC1 with no on PC2 with vpn using Radmin. game on PC2 did not pick up the info and event, assignment, dive where empty. On connecting PC2 to PC1 (host) event were picked up, while assignment was locked (no connection). When PC1 (host) launched the dive, PC2 picked up the info and dive started without a problem. I might be stupid but I cant feed the info to PC2 while server is on PC1, might be my router but who knows.

On using "install_certs_and_hosts.bat" it asked me the ip -> maybe don't ask and just force "127.0.0.1"?
when "install_certs_and_hosts.bat" writes strings to a file "#DeepDive Redirects, 127.0.0.1 drg.ghostship.dk, 127.0.0.1 services.ghostship.dk" if something was writen before it, the string will not be moved to new line.

127.0.0.1 drg.mod.io#DeepDive Redirects -> needs to move to the new line.

Maybe detect if serts are already installed. I bet you somone will install certificates twice or three times.

I will duplicate this just in case:
Idk maybe tray functionality is redundant? cause icon is duplicated in normal panel and in tray.
System Status checker didn't work for me (the marks part, program works perfectly)
Maybe start xampp automatically if it is installed, but in hidden state + with server on to avoid extra clicking for user (maybe option in settings to turn it off so can user can do it manually).
shut down xampp on exiting blackbeard?

P.S. sneaky png.
and what does the cGoalStateTime do? I never managed to recreate the discord goals is that it?

**Comment by 0P3N50URC3-F0R3V3R** [comment]
I just fixing the Hosts new line problem and i finished for today.

**Comment by Ravest95** [comment]
hmm I might need to change 127.0.0.1 to the Radmin ip (certs were installed for PC2, just xampp not launched). I will test it a bit later properly with phisical cable for lan.

About tray. I was thinking is it needed for BlackBeard (your call here), as I don't see the point of having the tray at all. With xampp in tray it is working like a server, let it do it's thing. With BlackBeard I want it on my screen to change things at all time. I will never need to start it hidden, as I will alway change something in it, and when I want to hide it it doesn't really need to go into tray too.
This is how it looks for me and what I would prefer.
![1](https://user-images.githubusercontent.com/105741067/226742519-36191f05-1a51-4c0d-9c24-902b003c7a73.jpg)
![2](https://user-images.githubusercontent.com/105741067/226742533-7ed3c4d6-56b3-4173-aadf-1b828c1633d2.jpg)

**Comment by 0P3N50URC3-F0R3V3R** [comment]
Well it is running so it is there... i am not able - currently - to turn that off, and BTW this program is for those too who are using on servers too.(not just simple players) And it is required for background hidden stufff.... i can only offer this:

![image](https://user-images.githubusercontent.com/94479523/226743362-9730a71c-d9c1-4772-9063-c8e6c0882525.png)

In this case when you minimise it will be on tray. And if you are playing you will not see anyway.

**Comment by 0P3N50URC3-F0R3V3R** [comment]
THX for the picture i will do stuff with it :D

**Comment by 0P3N50URC3-F0R3V3R** [comment]
I were thinking something of like this:
![image](https://user-images.githubusercontent.com/94479523/226747631-7be949a0-d768-42b0-b005-51ed2fb32e17.png)

Too bad that the rest of the text is hardcoded...

**Comment by 0P3N50URC3-F0R3V3R** [comment]
Fixed the Tray icon as you wanted.  In theory it will behave as you wanted to behave. It was a bit fiddly but i managed it, the tray only appears if you want it to appear.

**Comment by Ravest95** [comment]
I finnaly finished the UI, so I will explain in detail why it is sertain way, read it if you dare.

First to explain why current UI is overwhelming for ordinary user.

Deep Dives:
![1](https://user-images.githubusercontent.com/105741067/226795953-5af6af67-c4ae-4b9c-96db-d85b356f1b8a.jpg)
Label "OFFICIAL DEEPDIVE ..." -> no need, because user can figure out that it is official dives just by clicking in the list (number for seed will change, providing the info, that it is recorded dives). Part for "REQUIRED EVENTS ..." is used in new UI (described way lower). 
List -> Names are too long, it is really hard on the eyes (I do understand why but it is too much).
Label "You can use the ..." -> no need, as we can figure it out by clickin on the list or "Generate" button
Label "Note: The Seed ..." -> why not force generate random number if user types 0?
Label "MANUAL DEEPDIVE SEEDS" -> same as we know this.
Button "Version 1 Dive Seed ..." -> can be merged with 2 button.
Label "Max 10 digit" -> maybe cut down number to 10 digits if user types more the 10?
Label "ENDING DATE ..." -> no need, we can see "Set an end date:" under it.
Button "Set time to (Sec)" -> maybe "Set Timer (Sec)"?
Button "Set an end date:" -> maybe "Set End Date"?
Notes -> Maybe remove? I personally prefer notes to be tied to the deep dive name. For the personal list the area is too small, maybe add "Notes" tab?

Weekly Assignments:
![2](https://user-images.githubusercontent.com/105741067/226796012-d8112ad1-711e-400a-a86c-bd65c7787512.jpg)
Label "Weekly jobs are ..." -> I used that a bit differently in new UI.


Events:
![3](https://user-images.githubusercontent.com/105741067/226795996-86ac9606-5db1-47c3-994c-82edb0994c05.jpg)
Button "Random Freebeer event" -> no need, as we ether have free beer or not.
Label "SOME EVENTS" -> used differently in new UI.
Button "Randomize Main Event" -> half broken, as only certain evevnt are supported by game version.

Second how New UI should look. I forgot to rename some things, sorry. Main idea is to maintain constant structure. If you use warning in specific position, in specific color you must keep it across all tabs. That why I segregated to areas. Parameters -> things that you can change that will affect the game/program. Information -> things that will not change the game/program but will provide general info for the user. Notes -> warnings that are really important to know. List -> It is on the right to keep constant position (only 2 tabs use it).


Deep Dives:
![11](https://user-images.githubusercontent.com/105741067/226796029-8b83ed2b-fea5-4145-aa24-e1a99b1a891f.jpg)
Button "Generate" -> near the "Set an end date" to set current date +7 days from it. Near "Set time to (Sec)" to reset time to 604800.
Button "Seed" -> only 1 is needed as program can put the number in "Seed" and "SeedV2".
Buttons in Information -> grey color to distinguished from Parameters. Everything is just a sort of notes for selected Deep Dive.
List -> Search using the name or any parameter from Information. Dives are color coded to easy pick the version. Buttons "Official" and "Custom" to switch between official and custom dive lists.
Button "Add New Deep Dive" -> to not search it in the list. add a recoding of the dive manually (usefull for custom ones).

Weekly Assignments:
![12](https://user-images.githubusercontent.com/105741067/226796150-91fbb06e-ca9c-4613-beac-3047ab41974f.jpg)

Events:
![13](https://user-images.githubusercontent.com/105741067/226796072-01f8f1b4-2518-4feb-9d9b-0f9baafc82fd.jpg)
Information -> list of assignments and items that will be available in this event.
List -> search with Name or any info form the Information. Year in the name first for easier compare what was available when.
Button "No event" -> sepparate because it can be har to find it in the list (It can be longer in the future).

Game:
![14](https://user-images.githubusercontent.com/105741067/226796201-9626f9b7-16fe-4608-9ed6-2cda9e2a6de7.jpg)
To not clutter other tabs with info about game version. Maybe add links to launch game versions.
Pop up message if selected deep dive requires event, but user manually changed it.

Third how the structure of the program should look. This is done to make it easier adding/changing info on dives/events. I can just provide the files with info copied from excel.

Deepdive-Emulator -> main folder.
Deepdive-Emulator\xampp -> a seperate folder for xampp to not mix it with the blackbeard or other things.
Deepdive-Emulator\blackbeard -> a separate folder to not mix files.
Deepdive-Emulator\blackbeard\DeepDives -> folder for storing files with info on deep dives.
Deepdive-Emulator\blackbeard\DeepDives\125 -> one of the files on deep dive.

inside file 125:
Name=DeepDive125
Seed=57324384
DeepDive1=Crying Heart
Region1=Fungus Bogs
DeepDive2=Red Sorrow
Region=Dense Biozone

Deepdive-Emulator\blackbeard\Events -> same for events. Also idk if it is better but you can chain events it one command "{"ActiveEvents":["Xmas", "Xmas2021", "Xmas2022"]}"

**Comment by 0P3N50URC3-F0R3V3R** [comment]
You are very kind that you are sharing with me your opinion and take the design in your hands, my main goal with this was that i give the people something, that they can develop further.. I very hate online only stuff so if i can i am solving it that it couls work offline, and if i touched at least 1 or 2 people that takes on the project... as for the next bit and part of the text, i have to explein some things. I will attend to my code in the future but i will close this conversation since its gottent to the part where the taste and opinions and subjects are not matching. 

OK so yesterday, i figured that i will sum up the whole "interface" and "leftover files" stuff with this or the part that as "you dont like the interface" : Everything that you write is good and nice, that is why the source is public. So you can, and if you want, you can pull / clone everything if you dont like this, It is free and open to do so, if you dont like it as it is, clone it, and you can do with it the hell you want.  if i can i will even pull it if you want - but i never did that before in github so IDK how to do it XD i mean the merge.. 

IN the future i will do things as i see fit and you can do with your taste too. I mainly a programmer not an UI designer, but i think that we wont agree on what is needed and what is not. I am just glad if you are creating an own personal version with your own taste. Do it. But dont expect that i will create the interface as you see fit for you... as i saw you were able to create the ui as you like it. I dont mind, do it. This is the true beauty of the github. You can alter stuff and use it. 

Dont me abgry with me please - since i am not with you - that is why i asking you to do your own fork, and i will do mine :D We can - and will - collaborate, if you want ofc, but i dont want to redesign the whole thing just cuz you are dont like it...(I am attending with the users habits, and i see fit this way in this overwhelming way that i over explaining everything cuz i see that the users are - if you dont put in their faces the things - are wont take the time to read something separately otr they can be confused, so i am over explaining the things in my program) You ui is cleaned and wast, yes it is good too, but I did not see fit like this...

**Comment by 0P3N50URC3-F0R3V3R** [comment]
(I dont get the flipoff part, but... it might be a slang, so i will jump over it XD) 

Oh. OKay. I like one or two features of your pictures btw.  Like the whole coloring by version thing on the list, and the versions i will add - that wich one is required wich one is not... THAT is a neat feature. (it is possible in lazarus Tlist item? IDK i have to look after it.) And the DeepDive Database. I will implement it but with Sqlite3. not folders. (So it will be a Database with 3-4 rows of data.)... but the part of that you can save your own seeds is good :D I am not sure about the names, since tha game randomly names the expeditions based on the seed - i know i tested it - so it might be unnecesary to add it... Also how can i add/remove misson objjectives... on your ui i see this frequently but i did not seen any relation to it in the "htdocs" part so idk why the parameters are needed or where do you get them or generate... :\

**Comment by Ravest95** [comment]
Flip off -> show me the middle finger, I was annoying you so much.

About Deep Dive generation, when seeds id feed tho the game, It will interpret they seed how it wants. (some versions do one thing, some others), but It will always be fixed. If 2 people have identical version, no matter what they will have identical deep dives. That includes Name, Region, Objective, Mission, Side Objective, Warning, Anomaly. If you will try to replay the dive with the same version with the same seed, you will get the same dive (some randomness to spawning enemies will be there).

The whole information section was just like your Notes, but limited to 10 digits, and sepparated to their own fields (maybe dropdown list, that hides when you move mouse away is better?). It's not a way to correct the dive seed or something, it's just a way to record notes on your own (usually people will not write deep dive info into notes as it is long by hand, but a lot of players like to what missions were in the current deep dive, to go ahead knowingly, it is bad if you heave cryo and last mission is Industrial Sabotage). I will try to find the link for the excel that people usually use.

**Comment by Ravest95** [comment]
I didn't, never. You think too much of me. Im just an ordinary man who plays games. I have no knowladge on how to script, complie or other things. All I have is eyes and curiosity to press buttons or change values to see what will happen. I tried some scripting/modding games, thats it. When other people never think of what could be done, I try to find info, maybe poke around myself. The lite version of the xampp was me deleting the files and seeing will it break things (I am that dumb).
Where I saw coloring -> imagination. I have no idea if it is even possible. (I thought of game like UI, where you can add textures).

**Comment by 0P3N50URC3-F0R3V3R** [comment]
Oh i am sure it is possible :D I just dont know where to find it yet,(i've seen in more places befor like that) but i will maybe ask in forums or Chatgpt or something like that XD

Do not sell yourself so quickly :D There are frontend designers too... i was just think of that because you showed me an UI design... or is that photoshop? :D I just wanted to know where you designed that example... so the coloring is just a... paint or something on the pic?

**Comment by Ravest95** [comment]
What? You thought it was real, I mean yes, I am the photoshop master. I just opened some old game launchers for editing settings and copied thier UI functions. It was the closest thing I could find to your UI.

**Comment by 0P3N50URC3-F0R3V3R** [comment]
Ill close the issue for now, - With the "Some will be implemented" status :D

If there is a specific error, or feature request, lets handle it separately in other topics (it is more overviewable :D)
