### ISSUE TITLE
Offical mods, multiplayer and game behaviour (not really an issue)

### ISSUE THREAD

**Issue by Ravest95** [0P3N50URC3-F0R3V3R/blackbeard#6]
Might drop some info, because tool can be used in different ways with different programs.

Currenlty official modding workshop is implemented in stupid way. It is located on drg.mod.io (might have an extra mirrior os something) and requers connection on game launch to the website. Once you golberg emulator and start the game all mods will be deleted from your PC . Also mods can't be preserved with simple copy and drag to some folder (I will desribed it in the end)

Case 1: (You never use goldberg emulator, instead you use steam and will be online).
If you block connection (redirect to xampp) for drg.ghostship.dk and services.ghostship.dk your connection to steam network for a handshake will be lost, you will loose peer to peer connection (never will see lobbies online, this leads to using goldberg emulator).

Case 2: (You never use goldberg emulator, instead you use steam, but will be offline).
If you have new version, game will function normally (without the peer to peer obviously). If you use old version (Update 31), you will not enter the game, it will show the message that you must be online (this leads to goldberg emulator). In addition mods will be locked for full use ingame or just locked for turning them on/off (you can change config), files will remain on PC.

Case 3: (You use goldberg emulator).
Goldberg will convert all out request to local (read somewere in the ReadMe for goldberg, I might be wrong here). Maybe this is what leads to wierd game behavior. Game will delete all the files for mods, meaning when you will want to play normally you will download every single one of them again.
SOLUTION: in Deep Rock Galactic\FSD\Saved\Config\WindowsNoEditor\GameUserSettings.ini there is a "CurrentBranchName=" variable, it does not have a value, if you change it to "CurrentBranchName=public" and use goldberg all your mods will be preserved and game will load them (but you will not be able to turn them on/off ingame, only via config file editing).

Maybe notify user about mod files being deleted (if use goldberg emulator).
Maybe add info for "CurrentBranchName=public" into installation for goldberg emulator.
In addition to your Lanfix. In my project I set it Golberg Emulator up for a user with every neccesary setting to avoid user being lost and to reduce set up time. (drag and drop the files). Some things I've noticed that you might need to use/change (again up to you). I had DLC.txt -> you know to avoid accusation problems with piracy (by default Goldberg will unlock all DLC, and I forced to not do anything, smart users will do that on their own) path for installation can be different, depending on the version. Update 31 - has "Steamv139" folder, Update 32 - has "Steamv147", Update 36 (Season 02) has "Steamv151". In ColdClientLoader.ini there is "ExeCommandLine" for commands -nohmd will force the VR headset off (will golberg it game will try to launch VR by default). you know about -dx11, also there was -disablemodding that disables mods (It was really important for first versions of season 2 update, where game refused to launch offline).

EXTRA: (Unrelated at all, maybe usefull for you personally). I probably should dumb backed up mods for Season 02 on my page. 
Files:
Users\Public\mod.io\2475\metadata\state.json -> contains path for mods and their tags (for using Sanbox or normal save) and info (like description, author)
Users\Public\mod.io\2475\mods\ -> every folder here is a mod file.
Users\User\AppData\Local\mod.io\globalsettings.json -> file with path where mods are located.
Users\User\AppData\Local\mod.io\2475\S-1-5-21-4234091881-1074235106-1121824210-1001\user.json -> user subscriptions to mods. S-1-5-21-4234091881-1074235106-1121824210-1001 is user id.

Mods can be preserved with the "CurrentBranchName=public" and file backup. BUT only if you have right version of the mods, you cant use new mod in older game. ALSO info about just put mod into "Deep Rock Galactic\FSD\Content\Paks" or rename it to Mod_D is wrong, it does not work for Season 1 and later.

Mods can be spoofed for online play. You can block connection for drg.mod.io and have sandbox mods with normal tag. Leading into legal cheats while playing online with random people.

**Comment by 0P3N50URC3-F0R3V3R** [comment]
Firstly.: I am not makingf this to fix the mods with goldberg, also the goldberg is not mandatory, its just an option, but you can use it with original too.

You can block goldberg with a built in switch to not to let the exe connect to anywhere exept the custom_broadcasts.txt
(Remove disable_lan_only.txt from the pack) (INCLUDING ANY EXTERNAL SITES)

Goldberg supports mods but only the steam ones:
Engine\Binaries\ThirdParty\Steamworks\Steamv151\Win64\steam_settings\mods.EXAMPLE\

Rename mods.EXAMPLE to mods, and create a folder to the mod(usually the ID number and put it inside of that), if the mod is Steam compatiblee it will load, if not, then not, it has to be tested.

But generally i dont care here about the mods, Wont fix here  DRG every problems.... if you start the game with -disablemodding it works without mods... the rest.... well it is not my concern yet, the goldberg in the pack is just a fix for real offline.

**Comment by SlejmUr** [comment]
> Currenlty official modding workshop is implemented in stupid way.
Official mod support (steamworks/steam workshop) is not been presented in the store page that lead to 3rd party mods like you said mod.io

> C1
I mean ofc you "lost connection" for the official lobbies, because the site tries to auth you (or something), it fail, result is you gonna be not connected

> C2
Firstly while you using bb or without? 
I guess if you do:
Games internally can connect to anywhere to verify they are up to date, maybe them doing so(?)

> C3
No idea what is the issue here

> Maybe notify user about mod files being deleted (if use goldberg emulator).
Modding the game and emulating is not same as I know.
Usually emulating anything could broke sooo much things, or rather I always expect it.

> Update 31 - has "Steamv139" folder, Update 32 - has "Steamv147", Update 36 (Season 02) has "Steamv151".
Yep, that is how their steam dll are updating, nothing fancy, goldberg will take care about them, you dont need to track them.

> EXTRA
Thank you for that extra info!
But this application & goldberg emu has nothing to do with mod.io and their managing to work.

> if you have right version of the mods, you cant use new mod in older game
As expected, either their code broke or the mod will break something.

> Mods can be spoofed for online play. You can block connection for drg.mod.io and have sandbox mods with normal tag. Leading into legal cheats while playing online with random people.
Yes you can, but again this is not a mod.io emulator or like that. And I dont think DRG players or the mod.io team/devs would be happy with that.

**Comment by 0P3N50URC3-F0R3V3R** [comment]
So basicly, i will leave this in archive, and mark as closed, i am not attending with Blackbeard or the XAMPP part this cuz it is nothing to do with it.
